"use client";

import { useState } from "react";
import { Lightbulb, X } from "lucide-react";
import { IdeaSuggestions } from "./idea-suggestions";

export function DashboardIdeaModal({ onSelect }: { onSelect: (prompt: string) => void }) {
  const [open, setOpen] = useState(false);
  if (!open) return <button type="button" onClick={() => setOpen(true)} aria-haspopup="dialog" className="group inline-flex items-center gap-1.5 rounded-full border border-line bg-muted/70 px-2.5 py-1.5 text-[11px] font-semibold text-ink transition-all duration-200 hover:-translate-y-0.5 hover:border-violet-400/60 hover:bg-violet-500/10 hover:text-violet-700 hover:shadow-sm hover:shadow-violet-500/10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400 dark:hover:text-violet-300"><Lightbulb className="h-3.5 w-3.5 text-violet-600 transition-transform group-hover:rotate-6 group-hover:scale-110" /> Ideas <span className="rounded-full bg-elevated px-1.5 py-0.5 text-[9px] text-ink-muted transition-colors group-hover:text-violet-600">6</span></button>;
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-ink/60 p-4 backdrop-blur-sm" onClick={() => setOpen(false)}><div role="dialog" aria-modal="true" aria-labelledby="copilot-ideas-title" className="w-full max-w-2xl overflow-hidden rounded-3xl border border-line bg-elevated shadow-2xl shadow-ink/20" onClick={(e) => e.stopPropagation()}><div className="flex items-center gap-3 border-b border-line px-5 py-4"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-500/10 text-violet-600"><Lightbulb className="h-4 w-4" /></span><div className="flex-1"><h2 id="copilot-ideas-title" className="text-sm font-semibold text-ink">What would you like to automate?</h2><p className="text-[11px] text-ink-muted">Start from an idea or describe your own goal in the Copilot box.</p></div><button type="button" onClick={() => setOpen(false)} className="rounded-lg p-2 text-ink-muted transition-colors hover:bg-muted hover:text-ink focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-violet-400" aria-label="Close ideas"><X className="h-4 w-4" /></button></div><div className="max-h-[70vh] overflow-y-auto p-5"><IdeaSuggestions onSelect={(prompt) => { setOpen(false); onSelect(prompt); }} /></div></div></div>;
}
