"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sealSync = exports.seal = exports.redact = exports.openSync = exports.isEnvelopeBlob = exports.encryptLegacy = exports.encryptJson = exports.encodeSealed = exports.decryptLegacy = exports.decryptJson = exports.decodeSealed = exports.LocalKms = void 0;
var envelope_1 = require("./envelope");
Object.defineProperty(exports, "LocalKms", { enumerable: true, get: function () { return envelope_1.LocalKms; } });
Object.defineProperty(exports, "decodeSealed", { enumerable: true, get: function () { return envelope_1.decodeSealed; } });
Object.defineProperty(exports, "decryptJson", { enumerable: true, get: function () { return envelope_1.decryptJson; } });
Object.defineProperty(exports, "decryptLegacy", { enumerable: true, get: function () { return envelope_1.decryptLegacy; } });
Object.defineProperty(exports, "encodeSealed", { enumerable: true, get: function () { return envelope_1.encodeSealed; } });
Object.defineProperty(exports, "encryptJson", { enumerable: true, get: function () { return envelope_1.encryptJson; } });
Object.defineProperty(exports, "encryptLegacy", { enumerable: true, get: function () { return envelope_1.encryptLegacy; } });
Object.defineProperty(exports, "isEnvelopeBlob", { enumerable: true, get: function () { return envelope_1.isEnvelopeBlob; } });
Object.defineProperty(exports, "open", { enumerable: true, get: function () { return envelope_1.open; } });
Object.defineProperty(exports, "openSync", { enumerable: true, get: function () { return envelope_1.openSync; } });
Object.defineProperty(exports, "redact", { enumerable: true, get: function () { return envelope_1.redact; } });
Object.defineProperty(exports, "seal", { enumerable: true, get: function () { return envelope_1.seal; } });
Object.defineProperty(exports, "sealSync", { enumerable: true, get: function () { return envelope_1.sealSync; } });
